package jet.android2.modelo;

import java.util.*;
import gerapp.app.*;
import jet.wrappers.base.*;
import jet.wrappers.android.*;
import gerapp.modelo.*;

public class Agregado
{
  protected static String nl;
  public static synchronized Agregado create(String lineSeparator)
  {
    nl = lineSeparator;
    Agregado result = new Agregado();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "package ";
  protected final String TEXT_2 = ".modelo.agregado;" + NL + "" + NL + "import java.util.List;" + NL + "import java.util.ArrayList;" + NL + "import ";
  protected final String TEXT_3 = ".framework.log.DCLog;" + NL + "import ";
  protected final String TEXT_4 = ".modelo.*;" + NL + "" + NL + "" + NL + "public class ";
  protected final String TEXT_5 = "Agregado implements ";
  protected final String TEXT_6 = "AgregadoI" + NL + "{" + NL + "" + NL + "\tprivate final int QTDE_LOG_LAZY_LOADER = 4;" + NL + "\t/*" + NL + "\tprivate ";
  protected final String TEXT_7 = "Carregador carregador = null;" + NL + "\tprivate ";
  protected final String TEXT_8 = "Carregador getCarregador() {" + NL + "\t\tif (carregador==null) {" + NL + "\t\t\tcarregador = new ";
  protected final String TEXT_9 = "Carregador();" + NL + "\t\t}" + NL + "\t\treturn carregador;" + NL + "\t}" + NL + "\t" + NL + "\tpublic void setConexaoCarregador(DaoConexao conexao) {" + NL + "\t\tgetCarregador().setConexao(conexao);" + NL + "\t\t";
  protected final String TEXT_10 = "if (vo.";
  protected final String TEXT_11 = "_";
  protected final String TEXT_12 = " != null)" + NL + "\t\t\tvo.";
  protected final String TEXT_13 = "_";
  protected final String TEXT_14 = ".setConexaoCarregador(conexao);" + NL + "\t\t";
  protected final String TEXT_15 = NL + "\t}" + NL + "\t*/" + NL + "\t" + NL + "\tprivate ";
  protected final String TEXT_16 = " vo;" + NL + "\tpublic ";
  protected final String TEXT_17 = "Agregado(";
  protected final String TEXT_18 = " item) {" + NL + "\t\tvo = item;" + NL + "\t}" + NL + "\t" + NL + "\t";
  protected final String TEXT_19 = NL + "\t" + NL + "\tprivate ";
  protected final String TEXT_20 = " ";
  protected final String TEXT_21 = ";" + NL + "\tpublic void set";
  protected final String TEXT_22 = "_";
  protected final String TEXT_23 = "(";
  protected final String TEXT_24 = " valor)" + NL + "\t{\t" + NL + "\t\tvo.set";
  protected final String TEXT_25 = "(0);" + NL + "\t\t";
  protected final String TEXT_26 = " = valor;" + NL + "\t} " + NL + "\tpublic ";
  protected final String TEXT_27 = " get";
  protected final String TEXT_28 = "_";
  protected final String TEXT_29 = "() " + NL + "\t{\t" + NL + "\t//\tif (";
  protected final String TEXT_30 = "==null &&" + NL + "\t//\t\t\tvo.get";
  protected final String TEXT_31 = "LazyLoader() !=0)" + NL + "\t//\t{" + NL + "\t//\t\t";
  protected final String TEXT_32 = "Servico srv = FabricaServico.getInstancia().get";
  protected final String TEXT_33 = "Servico(FabricaServico.TIPO_SQLITE);" + NL + "\t//\t\t";
  protected final String TEXT_34 = " = srv.getById(vo.get";
  protected final String TEXT_35 = "LazyLoader());" + NL + "\t//\t\tDCLog.dStack(DCLog.LAZY_LOADER, this, \"";
  protected final String TEXT_36 = ".get";
  protected final String TEXT_37 = "_";
  protected final String TEXT_38 = "()\",QTDE_LOG_LAZY_LOADER);" + NL + "  \t//\t}" + NL + "\t\treturn ";
  protected final String TEXT_39 = ";" + NL + "\t} " + NL + "\t";
  protected final String TEXT_40 = NL + "\t/*  AutoRelacionamento" + NL + "\t";
  protected final String TEXT_41 = NL + "\tpublic void addLista";
  protected final String TEXT_42 = "_";
  protected final String TEXT_43 = "(";
  protected final String TEXT_44 = " value)" + NL + "\t{\t" + NL + "\t\t";
  protected final String TEXT_45 = " = value;" + NL + "\t} " + NL + "\tpublic ";
  protected final String TEXT_46 = " getCorrente";
  protected final String TEXT_47 = "_";
  protected final String TEXT_48 = "()" + NL + "\t{\t" + NL + "\t\treturn ";
  protected final String TEXT_49 = ";" + NL + "\t} " + NL + "\t";
  protected final String TEXT_50 = NL + "\t*/" + NL + "\t";
  protected final String TEXT_51 = NL + "\t";
  protected final String TEXT_52 = NL + " \t" + NL + " \t";
  protected final String TEXT_53 = NL + "\tprivate ";
  protected final String TEXT_54 = " ";
  protected final String TEXT_55 = ";" + NL + "\tpublic void set";
  protected final String TEXT_56 = "_";
  protected final String TEXT_57 = "(";
  protected final String TEXT_58 = " value) " + NL + "\t{\t" + NL + "\t\t";
  protected final String TEXT_59 = " = value;" + NL + "\t} " + NL + "\tpublic ";
  protected final String TEXT_60 = " get";
  protected final String TEXT_61 = "_";
  protected final String TEXT_62 = "() " + NL + "\t{\t" + NL + "\t\treturn ";
  protected final String TEXT_63 = ";" + NL + "\t} " + NL + "\t";
  protected final String TEXT_64 = NL + " \t" + NL + " \t" + NL + " \t";
  protected final String TEXT_65 = NL + "\tpublic boolean existeLista";
  protected final String TEXT_66 = "_";
  protected final String TEXT_67 = "() {" + NL + "\t\treturn lista";
  protected final String TEXT_68 = "!= null; " + NL + "\t}" + NL + "\tprivate List<";
  protected final String TEXT_69 = "> lista";
  protected final String TEXT_70 = ";" + NL + "\tprivate boolean daoLista";
  protected final String TEXT_71 = " = false;" + NL + "\tpublic void setLista";
  protected final String TEXT_72 = "_";
  protected final String TEXT_73 = "(List<";
  protected final String TEXT_74 = "> value)" + NL + "\t{\t" + NL + "\t\tlista";
  protected final String TEXT_75 = " = value;" + NL + "\t}" + NL + "\tpublic void setLista";
  protected final String TEXT_76 = "_";
  protected final String TEXT_77 = "ByDao(List<";
  protected final String TEXT_78 = "> value)" + NL + "\t{\t" + NL + "\t//\tlista";
  protected final String TEXT_79 = " = value;" + NL + "\t//\tdaoLista";
  protected final String TEXT_80 = " = (value!=null);" + NL + "\t}  " + NL + "\tpublic List<";
  protected final String TEXT_81 = "> getLista";
  protected final String TEXT_82 = "_";
  protected final String TEXT_83 = "()" + NL + "\t{\t" + NL + "\t//\tif (!daoLista";
  protected final String TEXT_84 = ")" + NL + "    //    {" + NL + "    //    ";
  protected final String TEXT_85 = "Servico srv = FabricaServico.getInstancia().get";
  protected final String TEXT_86 = "Servico(FabricaServico.TIPO_SQLITE);" + NL + "\t//\tlista";
  protected final String TEXT_87 = " = srv.getPor";
  protected final String TEXT_88 = "(vo.getId());" + NL + "\t//\tDCLog.dStack(DCLog.LAZY_LOADER, this, \"";
  protected final String TEXT_89 = ".getLista";
  protected final String TEXT_90 = "_";
  protected final String TEXT_91 = "()\",QTDE_LOG_LAZY_LOADER);" + NL + "    //    }" + NL + "\t \treturn lista";
  protected final String TEXT_92 = ";" + NL + "\t} " + NL + "\tpublic List<";
  protected final String TEXT_93 = "> getLista";
  protected final String TEXT_94 = "_";
  protected final String TEXT_95 = "Original()" + NL + "\t{\t" + NL + "\t\treturn lista";
  protected final String TEXT_96 = ";" + NL + "\t} " + NL + "\tpublic List<";
  protected final String TEXT_97 = "> getLista";
  protected final String TEXT_98 = "_";
  protected final String TEXT_99 = "(int qtde)" + NL + "\t{\t" + NL + "    //    ";
  protected final String TEXT_100 = "Servico srv = FabricaServico.getInstancia().get";
  protected final String TEXT_101 = "Servico(FabricaServico.TIPO_SQLITE);" + NL + "\t//\tlista";
  protected final String TEXT_102 = " = srv.getPor";
  protected final String TEXT_103 = "(vo.getContexto().getContext(), vo.getId());" + NL + "\t//\tDCLog.dStack(DCLog.LAZY_LOADER, this, \"";
  protected final String TEXT_104 = ".getLista";
  protected final String TEXT_105 = "_";
  protected final String TEXT_106 = "()\",QTDE_LOG_LAZY_LOADER);" + NL + "\t\treturn lista";
  protected final String TEXT_107 = ";" + NL + "\t} " + NL + "\tpublic void addLista";
  protected final String TEXT_108 = "_";
  protected final String TEXT_109 = "(";
  protected final String TEXT_110 = " value) " + NL + "\t{\t" + NL + "\t\tcriaVaziaLista";
  protected final String TEXT_111 = "_";
  protected final String TEXT_112 = "();" + NL + "\t\tlista";
  protected final String TEXT_113 = ".add(value);" + NL + "\t//\tdaoLista";
  protected final String TEXT_114 = " = true;" + NL + "\t} " + NL + "\tpublic ";
  protected final String TEXT_115 = " getCorrente";
  protected final String TEXT_116 = "_";
  protected final String TEXT_117 = "()" + NL + "\t{\t" + NL + "\t\tif (lista";
  protected final String TEXT_118 = "==null) return null;" + NL + "\t\treturn lista";
  protected final String TEXT_119 = ".get(lista";
  protected final String TEXT_120 = ".size()-1);" + NL + "\t} " + NL + "\tpublic void criaVaziaLista";
  protected final String TEXT_121 = "_";
  protected final String TEXT_122 = "() {" + NL + "\t\tif (lista";
  protected final String TEXT_123 = " == null)" + NL + "        {" + NL + "        \tlista";
  protected final String TEXT_124 = " = new ArrayList<";
  protected final String TEXT_125 = ">();" + NL + "        }" + NL + "\t}" + NL + "\t";
  protected final String TEXT_126 = NL + "}";
  protected final String TEXT_127 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
Recursos recursos = (Recursos) argument;  
ClasseWrapper classe = (ClasseWrapper) recursos.getClasse();
Configuracao conf = recursos.getConfiguracao();

    stringBuffer.append(TEXT_1);
    stringBuffer.append( conf.getNamespaceExtendido() );
    stringBuffer.append(TEXT_2);
    stringBuffer.append( conf.getNamespaceExtendido() );
    stringBuffer.append(TEXT_3);
    stringBuffer.append( conf.getNamespaceExtendido() );
    stringBuffer.append(TEXT_4);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_5);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_6);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_7);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_8);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_9);
    
		Iterator<RelacionamentoWrapper> iterador2 = classe.obtemListaComChaveEstrangeira().iterator();
		while (iterador2.hasNext()) {
		RelacionamentoWrapper relac = iterador2.next();
		ClasseWrapper classeOposta = relac.getClasseOposta();
		
    stringBuffer.append(TEXT_10);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_11);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_12);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_13);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_14);
    
		}
     	
    stringBuffer.append(TEXT_15);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_16);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_17);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_18);
    
	Iterator<RelacionamentoWrapper> iterador = classe.obtemListaComChaveEstrangeiraComUsuario().iterator();
	while (iterador.hasNext()) {
	RelacionamentoWrapper relac = iterador.next();
	ClasseWrapper classeOposta = relac.getClasseOposta();
	
    stringBuffer.append(TEXT_19);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_20);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_21);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_22);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_23);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_24);
    stringBuffer.append( relac.getNomePropriedade() );
    stringBuffer.append(TEXT_25);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_26);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_27);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_28);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_29);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_30);
    stringBuffer.append( relac.getNomePropriedade() );
    stringBuffer.append(TEXT_31);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_32);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_33);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_34);
    stringBuffer.append( relac.getNomePropriedade() );
    stringBuffer.append(TEXT_35);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_36);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_37);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_38);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_39);
     if (classe.getId()==classeOposta.getId()) {
    stringBuffer.append(TEXT_40);
     } 
    stringBuffer.append(TEXT_41);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_42);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_43);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_44);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_45);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_46);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_47);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_48);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_49);
     if (classe.getId()==classeOposta.getId()) {
    stringBuffer.append(TEXT_50);
     } 
    stringBuffer.append(TEXT_51);
    
	}
 	
    stringBuffer.append(TEXT_52);
    
	Iterator<RelacionamentoWrapper> iterador1x1 = classe.obtemListaUmPraUm().iterator();
	while (iterador1x1.hasNext()) {
	RelacionamentoWrapper relac = iterador1x1.next();
	ClasseWrapper classeOposta = relac.getClasseOposta();
	
    stringBuffer.append(TEXT_53);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_54);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_55);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_56);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_57);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_58);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_59);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_60);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_61);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_62);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_63);
    
	}
 	
    stringBuffer.append(TEXT_64);
    
	Iterator<RelacionamentoWrapper> iteradorN = classe.obtemListaSemChaveEstrangeira().iterator();
	while (iteradorN.hasNext()) {
	RelacionamentoWrapper relac = iteradorN.next();
	ClasseWrapper classeOposta = relac.getClasseOposta();
	
    stringBuffer.append(TEXT_65);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_66);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_67);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_68);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_69);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_70);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_71);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_72);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_73);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_74);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_75);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_76);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_77);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_78);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_79);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_80);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_81);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_82);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_83);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_84);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_85);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_86);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_87);
    stringBuffer.append( relac.getNomeRelacionamentoOposto() );
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_88);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_89);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_90);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_91);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_92);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_93);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_94);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_95);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_96);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_97);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_98);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_99);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_100);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_101);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_102);
    stringBuffer.append( relac.getNomeRelacionamentoOposto() );
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_103);
    stringBuffer.append( classe.getNomeParaClasse() );
    stringBuffer.append(TEXT_104);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_105);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_106);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_107);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_108);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_109);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_110);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_111);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_112);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_113);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_114);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_115);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_116);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_117);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_118);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_119);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_120);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_121);
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_122);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_123);
    stringBuffer.append( classeOposta.getNomeParaVariavel() );
    stringBuffer.append( relac.getNomeRelacionamento() );
    stringBuffer.append(TEXT_124);
    stringBuffer.append( classeOposta.getNomeParaClasse() );
    stringBuffer.append(TEXT_125);
    
	}
	
    stringBuffer.append(TEXT_126);
    stringBuffer.append(TEXT_127);
    return stringBuffer.toString();
  }
}
