<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classes"
    nsURI="http:///classes.ecore" nsPrefix="classes">
  <eClassifiers xsi:type="ecore:EClass" name="Motor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modelo" lowerBound="1"
        eType="#//Modelo" eOpposite="#//Modelo/Motor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpoint" lowerBound="1"
        upperBound="-1" eType="#//ItemCheckpoint" eOpposite="#//ItemCheckpoint/Motor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoModelo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modelo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Marca" lowerBound="1" eType="#//Marca"
        eOpposite="#//Marca/Modelo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Motor" lowerBound="1" upperBound="-1"
        eType="#//Motor" eOpposite="#//Motor/Modelo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoModelo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoModelo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marca">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modelo" lowerBound="1"
        upperBound="-1" eType="#//Modelo" eOpposite="#//Modelo/Marca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PontoLubrificacaoMarca"
        lowerBound="1" upperBound="-1" eType="#//PontoLubrificacaoMarca" eOpposite="#//PontoLubrificacaoMarca/Marca"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoVeiculo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpoint" lowerBound="1"
        upperBound="-1" eType="#//ItemCheckpoint" eOpposite="#//ItemCheckpoint/TipoVeiculo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PontoLubrificacaoMarca"
        lowerBound="1" upperBound="-1" eType="#//PontoLubrificacaoMarca" eOpposite="#//PontoLubrificacaoMarca/TipoVeiculo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Checkpoint" lowerBound="1"
        upperBound="-1" eType="#//Checkpoint" eOpposite="#//Checkpoint/TipoVeiculo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoTipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoTipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LubrificanteEspecificacao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EspecificacaoProduto" lowerBound="1"
        eType="#//EspecificacaoProduto" eOpposite="#//EspecificacaoProduto/LubrificanteEspecificacao"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lubrificante" lowerBound="1"
        eType="#//Lubrificante" eOpposite="#//Lubrificante/LubrificanteEspecificacao"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoProduto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lubrificante">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LubrificanteEspecificacao"
        lowerBound="1" upperBound="-1" eType="#//LubrificanteEspecificacao" eOpposite="#//LubrificanteEspecificacao/Lubrificante"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoProduto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoLubrificante" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idIpiranga" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idFabricadoConcorrente"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusVolumeLitros" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fatorConversao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoJetoil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EspecificacaoProduto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LubrificanteEspecificacao"
        lowerBound="1" upperBound="-1" eType="#//LubrificanteEspecificacao" eOpposite="#//LubrificanteEspecificacao/EspecificacaoProduto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpointEspecificacao"
        lowerBound="1" upperBound="-1" eType="#//ItemCheckpointEspecificacao" eOpposite="#//ItemCheckpointEspecificacao/EspecificacaoProduto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EspecificacaoProdutoSecao"
        lowerBound="1" upperBound="-1" eType="#//EspecificacaoProdutoSecao" eOpposite="#//EspecificacaoProdutoSecao/EspecificacaoProduto"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Secao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EspecificacaoProdutoSecao"
        lowerBound="1" upperBound="-1" eType="#//EspecificacaoProdutoSecao" eOpposite="#//EspecificacaoProdutoSecao/Secao"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Checkpoint" lowerBound="1"
        upperBound="-1" eType="#//Checkpoint" eOpposite="#//Checkpoint/Secao"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoDepartamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoSecao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoSecao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoriaJetoil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EspecificacaoProdutoSecao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EspecificacaoProduto" lowerBound="1"
        eType="#//EspecificacaoProduto" eOpposite="#//EspecificacaoProduto/EspecificacaoProdutoSecao"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Secao" lowerBound="1" eType="#//Secao"
        eOpposite="#//Secao/EspecificacaoProdutoSecao"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoDepartamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoSecao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemCheckpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpointEspecificacao"
        lowerBound="1" upperBound="-1" eType="#//ItemCheckpointEspecificacao" eOpposite="#//ItemCheckpointEspecificacao/ItemCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoVeiculo" lowerBound="1"
        eType="#//TipoVeiculo" eOpposite="#//TipoVeiculo/ItemCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Motor" lowerBound="1" eType="#//Motor"
        eOpposite="#//Motor/ItemCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Checkpoint" lowerBound="1"
        eType="#//Checkpoint" eOpposite="#//Checkpoint/ItemCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoModelo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoTipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anoFabricacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoCombustivel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoCambio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroCheckpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodoTroca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoFerramenta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aditivoRadiador" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemCheckpointEspecificacao">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EspecificacaoProduto" lowerBound="1"
        eType="#//EspecificacaoProduto" eOpposite="#//EspecificacaoProduto/ItemCheckpointEspecificacao"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpoint" lowerBound="1"
        eType="#//ItemCheckpoint" eOpposite="#//ItemCheckpoint/ItemCheckpointEspecificacao"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoModelo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMotor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anoFabricacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoCombustivel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoCambio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroCheckpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricao2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checkpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Secao" lowerBound="1" eType="#//Secao"
        eOpposite="#//Secao/Checkpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ItemCheckpoint" lowerBound="1"
        upperBound="-1" eType="#//ItemCheckpoint" eOpposite="#//ItemCheckpoint/Checkpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoVeiculo" lowerBound="1"
        eType="#//TipoVeiculo" eOpposite="#//TipoVeiculo/Checkpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StatusPorCheckpoint" lowerBound="1"
        upperBound="-1" eType="#//StatusPorCheckpoint" eOpposite="#//StatusPorCheckpoint/Checkpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoTipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroCheckpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoDepartamento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoSecao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoItemAtendimento"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkpointLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusCheckpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="StatusPorCheckpoint" lowerBound="1"
        upperBound="-1" eType="#//StatusPorCheckpoint" eOpposite="#//StatusPorCheckpoint/StatusCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoStatusCheckpoint"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoCheckpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idVolume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusPorCheckpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Checkpoint" lowerBound="1"
        eType="#//Checkpoint" eOpposite="#//Checkpoint/StatusPorCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StatusCheckpoint" lowerBound="1"
        eType="#//StatusCheckpoint" eOpposite="#//StatusCheckpoint/StatusPorCheckpoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroCheckpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoStatusCheckpoint"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PontoLubrificacaoMarca">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoVeiculo" lowerBound="1"
        eType="#//TipoVeiculo" eOpposite="#//TipoVeiculo/PontoLubrificacaoMarca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Marca" lowerBound="1" eType="#//Marca"
        eOpposite="#//Marca/PontoLubrificacaoMarca"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoMarca" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoTipoVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descricaoPonto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInclusao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataAlteracao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataInativacao" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoUsuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
